language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - stable
  - beta
  - nightly

before_script:
  - pip install https://github.com/huonw/travis-cargo/archive/handle-versions.zip --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coverage --no-sudo
  - rm -rf kcov
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
